name: ci checks
on: push
jobs:
  backend-checks:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name : formatting check
      run : ./mvnw spotless:check
      working-directory: backend
    - name: run tests
      run : ./mvnw compile test
      working-directory: backend

